#服务器端口
server:
  port: 8502

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://39.98.137.182:3306/seata?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: Lazylion0802.

# seata配置
seata:
  #registry:
  #  type: nacos
  #  nacos:
  #    server-addr: localhost
  #config:
  #  type: nacos
  #  nacos:
  #    server-addr: localhost
  tx-service-group: blade-seata-storage-group
  service:
    grouplist:
      default: 192.168.43.170:8091
    vgroup-mapping:
      blade-seata-storage-group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false
